name: Setup go environment
description: This reusable workflow sets up the go environment.

runs:
  using: "composite"

  steps:
    - name: Query cache for go artifacts
      uses: actions/cache@v1
      with:
        path: /home/runner/work/go
        key: taro-${{ runner.os }}-go-${{ env.GO_VERSION }}-${{ github.job }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          taro-${{ runner.os }}-go-${{ env.GO_VERSION }}-${{ github.job }}-${{ hashFiles('**/go.sum') }}
          taro-${{ runner.os }}-go-${{ env.GO_VERSION }}-${{ github.job }}-
          taro-${{ runner.os }}-go-${{ env.GO_VERSION }}-
          taro-${{ runner.os }}-go-

    - name: Setup go ${{ env.GO_VERSION }}
      uses: actions/setup-go@v2
      with:
        go-version: '${{ env.GO_VERSION }}'
